#!/bin/bash
#
#	~/.scripts/colors
#	Prints system colors
#

for i in {0..15}; do
	if [[ $i -eq 0 ]]; then
		tput setaf 15
	else
		tput setaf $i
	fi
	grep -e "^\*\.color$i:" ~/.Xresources
done
tput sgr0
exit 0
