#!/bin/bash
#
#	~/.scripts/polylocalhost
#	Checks if a localhost is running on specified ports,
#	adding a clickable icon to polybar.
#

icon=


#[ "$1" =~ '' ] && echo "MATCH"
pid=$(ps -ef | grep -e '.*server.*80[0-9][0-9]' | grep -v grep | awk '{print $2}')

case $1 in
	-k|k) kill $pid && notify-send "$icon [PID:$pid] Server Terminated" ;;
	-p|p) [ -n "$pid" ] && echo -e "$icon[8000]" || echo "" ;;
esac

