#!/bin/bash
#
#	~/.scripts/polyvolume
#
#	Displays the volume level and mute status
#	of pulseaudio in the polybar
#
#	TODO: rewrite this using IPC so that it's not
#	rechecking every second
#
sinkname=$(pactl list sinks | grep Name: | awk '{print $2}')

if [[ $sinkname = auto_null ]]; then
	echo ""
	exit 0
fi

mute=$(pactl list sinks | grep Mute | awk '{print $2}')

if [[ $mute = yes ]]; then
	echo " ---"
	exit 0
fi

pactl list sinks | grep -v Base | grep Volume | awk '{printf " %s", $5}'
